In [1]:
#Step 1
#Import Libraries

import time
import re
import pandas as pd
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from collections import OrderedDict #use to retrieve players name in original order

In [2]:
#Step 2
#Import URL
website = 'https://www.capology.com/club/west-ham/salaries/2016-2017/'
#website = "https://www.capology.com/club/manchester-united/salaries/2013-2014/"
#website = 'https://www.capology.com/club/arsenal/salaries/2015-2016/'
#website = 'https://www.capology.com/club/newcastle/salaries/

########################

#Step 3
#Define path where webdriver was downloaded #Not need anymore
path = "/Users/ismaelcisse/Downloads/chromedriver-mac-arm64/chromedriver"

#######################

#Step 4
#For the current version of selenium, you can't pass executable_path to Chrome() directly. 
#If you want to reference a specific downloaded version of ChromeDriver try this:
cService = webdriver.ChromeService(path = "/Users/ismaelcisse/Downloads/chromedriver-mac-arm64/chromedriver")

#Define driver variable
driver = webdriver.Chrome(service = cService) #dont close that page

#Chrome because it works well on it (can be Safari,Mozilla etc...)

######################

#Step 5
#Request to the website (It will display the url webpage)
driver.get(website)

In [3]:
#### TEST BUTTON ####
#Create a "close" button 
close_button = driver.find_element(By.XPATH,'/html/body/div/div[2]/div[1]/div[1]/button')

#Using click feature (want to display all matches instead Home/Away split by default)
close_button.click()

In [4]:
#Step 4
#For the current version of selenium, you can't pass executable_path to Chrome() directly. 
#If you want to reference a specific downloaded version of ChromeDriver try this:
#cService = webdriver.ChromeService(path = "/Users/ismaelcisse/Downloads/chromedriver-mac-arm64/chromedriver")

#Define driver variable
#driver = webdriver.Chrome(service = cService) #dont close that page

#Chrome because it works well on it (can be Safari,Mozilla etc...)

In [5]:
#Step 5
#Request to the website (It will display the url webpage)
#driver.get(website)

In [3]:
#Alternative Step
datas5 = driver.find_elements(By.XPATH, '//*[@id="panel"]/div[3]/div/div[6]/div[2]')
# Need to create a loop in order to collect all teams link of the championship 
# Assuming the link is in the 'href' attribute
for data in datas5:
    for i in range(1,21):
        xpath = f"./a[{i}]"
        link = data.find_element(By.XPATH,xpath).get_attribute('href')
        print(link)
        #club_link.append(link)
        
#Need to create a loop with regex to retrieve club name from each link

https://www.capology.com/club/arsenal/salaries/2016-2017/
https://www.capology.com/club/bournemouth/salaries/2016-2017/
https://www.capology.com/club/burnley/salaries/2016-2017/
https://www.capology.com/club/chelsea/salaries/2016-2017/
https://www.capology.com/club/crystal-palace/salaries/2016-2017/
https://www.capology.com/club/everton/salaries/2016-2017/
https://www.capology.com/club/hull-city/salaries/2016-2017/
https://www.capology.com/club/leicester/salaries/2016-2017/
https://www.capology.com/club/liverpool/salaries/2016-2017/
https://www.capology.com/club/manchester-city/salaries/2016-2017/
https://www.capology.com/club/manchester-united/salaries/2016-2017/
https://www.capology.com/club/middlesbrough/salaries/2016-2017/
https://www.capology.com/club/southampton/salaries/2016-2017/
https://www.capology.com/club/stoke-city/salaries/2016-2017/
https://www.capology.com/club/sunderland/salaries/2016-2017/
https://www.capology.com/club/swansea/salaries/2016-2017/
https://www.capology.com/club/tottenham/salaries/2016-2017/
https://www.capology.com/club/watford/salaries/2016-2017/
https://www.capology.com/club/west-bromwich/salaries/2016-2017/
https://www.capology.com/club/west-ham/salaries/2016-2017/

In [4]:
#Step 6
#Extract data from a table
#datas = driver.find_elements(By.TAG_NAME,'tr')
#datas2 = driver.find_elements(By.XPATH,'//tbody')
#datas3 = driver.find_elements(By.ID,'table')

#Extract data from a table
datas4 = driver.find_elements(By.XPATH, '//table[@id="table"]/tbody[1]/tr')

#Create lists to store collected elements
player_names_empty = []
salary_week_empty = []
salary_year_empty = []
bonus_empty = []
contract_signed_date_empty = []
contract_expiration_date_empty = []
conct_year_remaining_empty = []
player_position_empty = []
pos_detailled_empty = []
age_empty = []
country_empty = []
age_test_empty =[]

#for data in datas:
#    print(data.text)

#LOOP TO RETRIEVE ELEMENT AND STORE IT IN LISTS ABOVE
#for data in datas4:
#    print(data.text)
#    player_names.append(data.find_element(By.XPATH, './td[1]').text)
#    salary_week.append(data.find_element(By.XPATH, './td[3]').text)
#    salary_year.append(data.find_element(By.XPATH, './td[4]').text)
#    bonus.append(data.find_element(By.XPATH, './td[5]').text)
#    contract_signed_date.append(data.find_element(By.XPATH, './td[6]').text)
#    contract_expiration_date.append(data.find_element(By.XPATH, './td[7]').text)
#    conct_year_remaining.append(data.find_element(By.XPATH, './td[8]').text)
#    player_position.append(data.find_element(By.XPATH, './td[11]').text)
#    pos_detailled.append(data.find_element(By.XPATH, './td[12]').text)
#    age.append(data.find_element(By.XPATH, './td[13]').text)
#    country.append(data.find_element(By.XPATH, './td[15]').text)

#    player_name = data.find_element(By.XPATH,'./td[3]')
    
#for match in matches:
    #date.append(match.find_element(By.XPATH,'./td[1]').text)
    #player_name = datas3.find_element(By.XPATH, './td[1]').text
    #player_names.append(player_name)

In [5]:
#Step 7
#TEST - Data Retrieving (other seasons)

#Age - Présence d'éléments vides - use regex way
for data in datas4:
    age_test_empty.append(data.find_element(By.XPATH,'./td[6]').text)
    #age_test_empty
#   age_test = data.find_element(By.XPATH,'./td[13]').text

# Retrieve non-empty strings in age list using list comprehension
regex = re.compile(r'.+')
age_non_empty_strings = [s for s in age_test_empty if regex.match(s)]
#non_empty_strings

###########################################################################################

#Salary per week - Présence d'éléments vides - use regex way
#for data in datas4:
    #salary_week_test = data.find_element(By.XPATH,'./td[3]').text
    #print(salary_week_test)
    
#Salary per week - Présence d'éléments vides - use regex way
#for data in datas4:
#    salary_week_empty.append(data.find_element(By.XPATH,'./td[2]').text)
    #print(salary_week_empty)
    
#regex = re.compile(r'.+') - Note for dataframe
#salary_week_wth_empty_str = [s for s in salary_week_empty if regex.match(s)] - Note for dataframe

###########################################################################################

#MODIF - retrieving € and ',' from salary per week 

#Salary per week - Présence d'éléments vides - use regex way
#for data in datas4:
#    salary_week_test = data.find_element(By.XPATH,'./td[2]').text
#    pattern = ','
#    number_without_comma = re.sub(pattern, '', salary_week_test)
#    matches_findall = re.findall(r'\d+', number_without_comma)
#    salary_week_empty.append(matches_findall)
    
for data in datas4:
    salary_week_test = data.find_element(By.XPATH,'./td[2]').text
    #salary_week_wth_euro = salary_week_test.replace('€', '')
    salary_week_wth_euro = salary_week_test.replace('£', '')
    salary_week_wth_comma = re.sub(r',', '', salary_week_wth_euro)
    salary_week_wth_space = salary_week_wth_comma.strip()
    salary_week_empty.append(salary_week_wth_space)
    
###########################################################################################

#Names - Présence doublons - use DictOrder way
#for data in datas4:
#    player_name_test = data.find_element(By.XPATH, './td[1]').text

# Initialize an empty OrderedDict to store unique player names while preserving order
unique_player_names_ordered = OrderedDict()

# Iterate over datas4 and add unique player names to the OrderedDict
for data in datas4:
    player_name = data.find_element(By.XPATH, './td[1]').text
    unique_player_names_ordered[player_name] = None

# Retrieve unique player names in the original order
player_names_empty = list(unique_player_names_ordered.keys())

###########################################################################################
    
#Salary per year - Présence d'éléments vides - use regex way
#for data in datas4:
#    salary_year_test = data.find_element(By.XPATH,'./td[4]').text

#Salary per year - Présence d'éléments vides - use regex way
#for data in datas4:
#    salary_year_empty.append(data.find_element(By.XPATH,'./td[3]').text)
    #print(salary_year_empty)
    
#regex = re.compile(r'.+') - Note for dataframe
#salary_year_wth_empty_str = [s for s in salary_year_empty if regex.match(s)] - Note for dataframe

###########################################################################################

#MODIF - retrieving € and ',' from salary per week 

#Salary per year - Présence d'éléments vides - use regex way
#for data in datas4:
#    salary_year_test = data.find_element(By.XPATH,'./td[3]').text
#    pattern = ','
#    number_without_comma = re.sub(pattern, '', salary_year_test)
#    matches_findall1 = re.findall(r'\d+', number_without_comma)
#    salary_year_empty.append(matches_findall1)
    #print(salary_year_empty)
    
for data in datas4:
    salary_year_test = data.find_element(By.XPATH,'./td[3]').text
    #salary_year_wth_euro = salary_year_test.replace('€', '')
    salary_year_wth_euro = salary_year_test.replace('£', '')
    salary_year_wth_comma = re.sub(r',', '', salary_year_wth_euro)
    salary_year_wth_space = salary_year_wth_comma.strip()
    salary_year_empty.append(salary_year_wth_space)
    
###########################################################################################
    
#Bonus - Présence d'éléments vides - use regex way
#for data in datas4:
#    bonus_test = data.find_element(By.XPATH,'./td[5]').text

###########################################################################################

#Position - Présence d'éléments vides - use regex way
#for data in datas4:
#    position_test = data.find_element(By.XPATH,'./td[11]').text

#Position - Présence d'éléments vides - use regex way
for data in datas4:
    player_position_empty.append(data.find_element(By.XPATH,'./td[5]').text)
    #print(player_position_empty)
    
regex = re.compile(r'.+')
player_position_wth_empty_str = [s for s in player_position_empty if regex.match(s)]

###########################################################################################

#Country - Présence d'éléments vides - use regex way
#for data in datas4:
#    country_test = data.find_element(By.XPATH,'./td[15]').text

#Country - Présence d'éléments vides - use regex way
for data in datas4:
    country_empty.append(data.find_element(By.XPATH,'./td[7]').text)
    #print(country_empty)
    
regex = re.compile(r'.+')
country_wth_empty_str = [s for s in country_empty if regex.match(s)]

###########################################################################################

In [6]:
#Step 8
###################################################################################################################

#NEW VERSION FROM ABOVE - MUCH BETTER
clubb_name = driver.find_element(By.XPATH,'//*[@id="panel"]/div[3]/div/div[2]/div[2]/div/h6[1]').text

# Retrieve club name with regex - Done
pattern1 = '(\w+\s?\w+)'
name = re.search(pattern1, clubb_name)
name1 = name.group(0)
name1

# Retrieve league with regex - Done
#pattern2 = '(\(\w+.\w+\))'
pattern2 = '\((\w+.\w+)\)'
name2 = re.search(pattern2, clubb_name)
league1 = name2.group(1)
league1

#league_regex = re.sub(r'()', '', name3)
#league_regex

#pattern2 = r'\((.*?)\)'
#name2 = re.search(pattern2, clubb_name)
#name3 = name2.group(1)
#name3

# Retrieve season with regex - Done
pattern3 = '\d+\-\d+'
name4 = re.search(pattern3, clubb_name)
season1 = name4.group(0)
#season1

In [7]:
# Step 9 - Arsenal Only
# Create dataframe (only for Arsenal)
#table = pd.DataFrame({'Player_Name': player_names_empty
#                      ,'Salary Per Week': salary_week_empty,
#                     'Salary Per Year': salary_year_empty,
#                     'Position': player_position_wth_empty_str,
#                     'Age': age_non_empty_strings,
#                     'Country': country_wth_empty_str,
#                     'Club':name1,'Season':season1,'League':league1})
#Quick Step
#Retrieve players with no info (Salary per Week and Salary per Year)
#table = table.drop(table[table['Salary Per Week']==''].index)

#Other Clubs
#table.loc[(table.Position == 'M'),'Position']='Midfielder'
#table.loc[(table.Position == 'F'),'Position']='Forward'
#table.loc[(table.Position == 'D'),'Position']='Defender'
#table.loc[(table.Position == 'K'),'Position']='Goalkeeper'

In [7]:
# Step 9 - Other Clubs
# Create dataframe (for other clubs to add)
table1 = pd.DataFrame({'Player_Name': player_names_empty
                      ,'Salary Per Week': salary_week_empty,
                     'Salary Per Year': salary_year_empty,
                     'Position': player_position_wth_empty_str,
                     'Age': age_non_empty_strings,
                     'Country': country_wth_empty_str,
                     'Club':name1,'Season':season1,'League':league1})

#Quick Step
#Retrieve players with no info (Salary per Week and Salary per Year)
table1 = table1.drop(table1[table1['Salary Per Week']==''].index)

#Other Clubs
table1.loc[(table1.Position == 'M'),'Position']='Midfielder'
table1.loc[(table1.Position == 'F'),'Position']='Forward'
table1.loc[(table1.Position == 'D'),'Position']='Defender'
table1.loc[(table1.Position == 'K'),'Position']='Goalkeeper'

In [8]:
table1.head()

,Player_Name,Salary Per Week,Salary Per Year,Position,Age,Country,Club,Season,League
0,André Ayew,80000,4160000,Forward,26,Ghana,West Ham,2016-2017,Premier League
1,José Fonte,75000,3900000,Defender,32,Portugal,West Ham,2016-2017,Premier League
2,Andy Carroll,70000,3640000,Forward,27,England,West Ham,2016-2017,Premier League
3,Sofiane Feghouli,65000,3380000,Forward,26,Algeria,West Ham,2016-2017,Premier League
4,Angelo Ogbonna,60000,3120000,Defender,28,Italy,West Ham,2016-2017,Premier League

In [9]:
#Step 10 - Creating excel file
#table.to_excel(r'/Users/ismaelcisse/Desktop/Capology Salaries/13_14/Capology_PL_2016-2017.xlsx', 
#               index=False, encoding="utf-8-sig")

In [9]:
#Step 10 bis - Write to existing excel file
path = "/Users/ismaelcisse/Desktop/Capology Salaries/13_14"
os.chdir(path)

# Read the existing Excel file into a DataFrame
existing_filename = "Capology_PL_2016-2017.xlsx"
table = pd.read_excel(existing_filename)

# Assuming df_new is the new DataFrame you want to add
#df_new = pd.DataFrame(data_new)
table1

# Concatenate the new DataFrame with the existing one
concatenated_table = pd.concat([table, table1], ignore_index=True)

# Save the concatenated DataFrame back to the Excel file
with pd.ExcelWriter(existing_filename, mode='w', engine='openpyxl') as writer:
    concatenated_table.to_excel(writer, index=False)